# Generated by Django 2.2 on 2019-07-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
